version: '3.1'
services:
  login-app:
    image: latest123/login-app
    build: .
    restart: always
    ports:
      - '7500:7500'
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - type: volume
        source: data
        target: /data/db
    ports:
      - '27018:27017'
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - '8081:8081'
volumes:
  data: null
